### ISSUE TITLE
Mouse wheel event can break PyVistaAxesGrid.py example

### ISSUE THREAD

**Issue by psavery** [Kitware/trame-vtk#32] opened 2023-03-23 00:39 UTC
When you start the `PyVistaAxesGrid.py` example, if you begin by moving the mouse wheel rather than a different kind of mouse interaction, the rendering canvas turns completely blank (and can only be restored through refreshing the page).

**Comment by jourdain** [comment] 2023-06-15 18:08
I think the issue is related to the initial camera state that get pushed to the client. 
We should try to reset the camera on the server before any client connect.

**Comment by banesullivan** [comment] 2023-06-15 18:15
I think a `plotter.reset_camera(render=False)` is needed. 

We automatically do this in PyVista's wrappings of these Views in:

https://github.com/pyvista/pyvista/blob/0e8df552f753362db8fed9dee93e7a7b1dec7f17/pyvista/trame/views.py#L14-L20

**Comment by jourdain** [comment] 2023-06-15 18:27
Fixed in https://github.com/Kitware/trame-vtk/commit/d08379621902bc541e8f12a5e0716aa70f55249d

**Closed by jourdain** 2023-06-15 18:27 UTC
